# Generated by Django 5.2 on 2025-04-15 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('student_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
