# Generated by Django 5.2 on 2025-04-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_student_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
